use aviation;

ALTER TABLE FLIGHTS
    MODIFY COLUMN DEPARTURE_TIME INT,
    MODIFY COLUMN DEPARTURE_DELAY INT,
    MODIFY COLUMN TAXI_OUT INT,
    MODIFY COLUMN WHEELS_OFF INT,
    MODIFY COLUMN SCHEDULED_TIME INT,
    MODIFY COLUMN ELAPSED_TIME INT,
    MODIFY COLUMN AIR_TIME INT,
    MODIFY COLUMN WHEELS_ON INT,
    MODIFY COLUMN TAXI_IN INT,
    MODIFY COLUMN ARRIVAL_TIME INT,
    MODIFY COLUMN ARRIVAL_DELAY INT,
    MODIFY COLUMN AIR_SYSTEM_DELAY INT,
    MODIFY COLUMN SECURITY_DELAY INT,
    MODIFY COLUMN AIRLINE_DELAY INT,
    MODIFY COLUMN LATE_AIRCRAFT_DELAY INT,
    MODIFY COLUMN WEATHER_DELAY INT;