USE AVIATION;

UPDATE FLIGHTS
SET
	AIRLINE = CASE AIRLINE WHEN '' THEN NULL ELSE AIRLINE END,
	DEPARTURE_TIME = CASE DEPARTURE_TIME WHEN '' THEN NULL ELSE DEPARTURE_TIME END,
    DEPARTURE_DELAY = CASE DEPARTURE_DELAY WHEN '' THEN NULL ELSE DEPARTURE_DELAY END,
    TAXI_OUT = CASE TAXI_OUT WHEN '' THEN NULL ELSE TAXI_OUT END,
    WHEELS_OFF = CASE WHEELS_OFF WHEN '' THEN NULL ELSE WHEELS_OFF END,
    SCHEDULED_TIME = CASE SCHEDULED_TIME WHEN '' THEN NULL ELSE SCHEDULED_TIME END,
    ELAPSED_TIME = CASE ELAPSED_TIME WHEN '' THEN NULL ELSE ELAPSED_TIME END,
    AIR_TIME = CASE AIR_TIME WHEN '' THEN NULL ELSE AIR_TIME END,
    WHEELS_ON = CASE WHEELS_ON WHEN '' THEN NULL ELSE WHEELS_ON END,
    TAXI_IN = CASE TAXI_IN WHEN '' THEN NULL ELSE TAXI_IN END,
    ARRIVAL_TIME = CASE ARRIVAL_TIME WHEN '' THEN NULL ELSE ARRIVAL_TIME END,
    ARRIVAL_DELAY = CASE ARRIVAL_DELAY WHEN '' THEN NULL ELSE ARRIVAL_DELAY END,
    AIR_SYSTEM_DELAY = CASE AIR_SYSTEM_DELAY WHEN '' THEN NULL ELSE AIR_SYSTEM_DELAY END,
    SECURITY_DELAY = CASE SECURITY_DELAY WHEN '' THEN NULL ELSE SECURITY_DELAY END,
    AIRLINE_DELAY = CASE AIRLINE_DELAY WHEN '' THEN NULL ELSE AIRLINE_DELAY END,
    LATE_AIRCRAFT_DELAY = CASE LATE_AIRCRAFT_DELAY WHEN '' THEN NULL ELSE LATE_AIRCRAFT_DELAY END,
    WEATHER_DELAY = CASE WEATHER_DELAY WHEN '' THEN NULL ELSE WEATHER_DELAY END;
    
