USE aviation;

select * from flights;

SELECT COUNT(DAY_OF_WEEK)  FROM flights ;

SELECT * FROM FLIGHTS LIMIT 10;

 SELECT count(DAY_OF_WEEK) AS TOTAL_WEEKDAY_FLIGHTS 
 FROM FLIGHTS 
 WHERE DAY_OF_WEEK IN (1,2,3,4,5) ;

#################Way 1
SELECT 
	(SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (1,2,3,4,5)) AS TOTAL_WEEKDAY_FLIGHTS,
	(SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (6,7)) AS TOTAL_WEEKEND_FLIGHTS;


#################Way 2
select count(*) as TOTAL_FLIGHTS_COUNT,
 count(case when DAY_OF_WEEK IN (1,2,3,4,5) then 1 else null end) as TOTAL_WEEKDAY_FLIGHTS,
 count(case when DAY_OF_WEEK IN (6,7) then 1 else null end) as TOTAL_WEEKEND_FLIGHTS
 from FLIGHTS;
 
 
 SELECT 
	(SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (1,2,3,4,5)) AS TOTAL_WEEKDAY_FLIGHTS,
    (SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (6,7)) AS TOTAL_WEEKEND_FLIGHTS,
    (SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (1,2,3,4,5)
 	GROUP BY DAY_OF_WEEK ORDER BY COUNT(DAY_OF_WEEK) DESC LIMIT 1) AS MAXIMUM_WEEKDAY_FLIGHTS,
    (SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (6,7)
	GROUP BY DAY_OF_WEEK ORDER BY COUNT(DAY_OF_WEEK) DESC LIMIT 1)  AS MAXIMUM_WEEKEND_FLIGHTS,
    (SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (1,2,3,4,5)
	GROUP BY DAY_OF_WEEK ORDER BY COUNT(DAY_OF_WEEK) LIMIT 1) AS MINIMUM_WEEKDAY_FLIGHTS,
    (SELECT COUNT(DAY_OF_WEEK) FROM FLIGHTS WHERE DAY_OF_WEEK IN (6,7)
	GROUP BY DAY_OF_WEEK ORDER BY COUNT(DAY_OF_WEEK) LIMIT 1) AS MINIMUM_WEEKEND_FLIGHTS,
    (SELECT ROUND(AVG(WEEKDAY_COUNT)) FROM (SELECT COUNT(DAY_OF_WEEK) AS WEEKDAY_COUNT 
    FROM FLIGHTS WHERE DAY_OF_WEEK IN (1,2,3,4,5) GROUP BY DAY_OF_WEEK) AS RESULTS) AS AVERAGE_WEEKDAY_FLIGHTS,
    (SELECT ROUND(AVG(WEEKEND_COUNT)) FROM (SELECT COUNT(DAY_OF_WEEK) AS WEEKEND_COUNT 
    FROM FLIGHTS WHERE DAY_OF_WEEK IN (6,7) GROUP BY DAY_OF_WEEK) AS RESULTS) AS AVERAGE_WEEKEND_FLIGHTS;
 
 
 
 
 
 
